# adhkar_data.py
# النص العربي هو الأصل، والترجمات هي معاني تقريبية للأذكار وليست بديلًا عن النص العربي.

ADHKAR_LANGUAGES = {
    "ar": {
        "flag": "🇸🇦",
        "name": "العربية",
        "label_arabic_text": "النص العربي",
        "label_meaning": "المعنى",
        "label_repeat": "التكرار",
        "label_source": "المصدر",
        "missing": "",
        "morning_title": "🌅 أذكار الصباح",
        "evening_title": "🌙 أذكار المساء",
        "dhikr_word": "الذكر",
        "translation_note": "",
        "done_morning": "✅ <b>أحسنت.</b>\n\nانتهيت من أذكار الصباح.\nنسأل الله أن يحفظك ويبارك يومك.",
        "done_evening": "✅ <b>أحسنت.</b>\n\nانتهيت من أذكار المساء.\nنسأل الله أن يحفظك في ليلتك.",
        "reminder_morning": "🌅 <b>تذكير أذكار الصباح</b>\n\nابدأ بقراءة أذكار الصباح الآن.",
        "reminder_evening": "🌙 <b>تذكير أذكار المساء</b>\n\nابدأ بقراءة أذكار المساء الآن.",
        "start_morning_button": "🌅 ابدأ أذكار الصباح",
        "start_evening_button": "🌙 ابدأ أذكار المساء",
    },
    "en": {
        "flag": "🇬🇧",
        "name": "English",
        "label_arabic_text": "Arabic text",
        "label_meaning": "Meaning in English",
        "label_repeat": "Repeat",
        "label_source": "Source",
        "missing": "Meaning in this language is being added.",
        "morning_title": "🌅 Morning Adhkar",
        "evening_title": "🌙 Evening Adhkar",
        "dhikr_word": "Dhikr",
        "translation_note": "Note: The Arabic text is the original. The translation is an approximate meaning.",
        "done_morning": "✅ <b>Well done.</b>\n\nYou finished the morning adhkar.",
        "done_evening": "✅ <b>Well done.</b>\n\nYou finished the evening adhkar.",
        "reminder_morning": "🌅 <b>Morning Adhkar Reminder</b>\n\nStart reading your morning adhkar now.",
        "reminder_evening": "🌙 <b>Evening Adhkar Reminder</b>\n\nStart reading your evening adhkar now.",
        "start_morning_button": "🌅 Start Morning Adhkar",
        "start_evening_button": "🌙 Start Evening Adhkar",
    },
    "de": {
        "flag": "🇩🇪",
        "name": "Deutsch",
        "label_arabic_text": "Arabischer Text",
        "label_meaning": "Bedeutung auf Deutsch",
        "label_repeat": "Wiederholung",
        "label_source": "Quelle",
        "missing": "Die Bedeutung in dieser Sprache wird noch hinzugefügt.",
        "morning_title": "🌅 Morgen-Adhkar",
        "evening_title": "🌙 Abend-Adhkar",
        "dhikr_word": "Dhikr",
        "translation_note": "Hinweis: Der arabische Text ist das Original. Die Übersetzung ist eine ungefähre Bedeutung.",
        "done_morning": "✅ <b>Sehr gut.</b>\n\nDu hast die Morgen-Adhkar beendet.",
        "done_evening": "✅ <b>Sehr gut.</b>\n\nDu hast die Abend-Adhkar beendet.",
        "reminder_morning": "🌅 <b>Erinnerung an Morgen-Adhkar</b>\n\nBeginne jetzt mit deinen Morgen-Adhkar.",
        "reminder_evening": "🌙 <b>Erinnerung an Abend-Adhkar</b>\n\nBeginne jetzt mit deinen Abend-Adhkar.",
        "start_morning_button": "🌅 Morgen-Adhkar starten",
        "start_evening_button": "🌙 Abend-Adhkar starten",
    },
    "fr": {
        "flag": "🇫🇷",
        "name": "Français",
        "label_arabic_text": "Texte arabe",
        "label_meaning": "Sens en français",
        "label_repeat": "Répétition",
        "label_source": "Source",
        "missing": "Le sens dans cette langue est en cours d’ajout.",
        "morning_title": "🌅 Adhkâr du matin",
        "evening_title": "🌙 Adhkâr du soir",
        "dhikr_word": "Dhikr",
        "translation_note": "Remarque : le texte arabe est l’original. La traduction est un sens approximatif.",
        "done_morning": "✅ <b>Très bien.</b>\n\nVous avez terminé les adhkâr du matin.",
        "done_evening": "✅ <b>Très bien.</b>\n\nVous avez terminé les adhkâr du soir.",
        "reminder_morning": "🌅 <b>Rappel des adhkâr du matin</b>\n\nCommencez vos adhkâr du matin maintenant.",
        "reminder_evening": "🌙 <b>Rappel des adhkâr du soir</b>\n\nCommencez vos adhkâr du soir maintenant.",
        "start_morning_button": "🌅 Commencer les adhkâr du matin",
        "start_evening_button": "🌙 Commencer les adhkâr du soir",
    },
    "es": {
        "flag": "🇪🇸",
        "name": "Español",
        "label_arabic_text": "Texto árabe",
        "label_meaning": "Significado en español",
        "label_repeat": "Repetición",
        "label_source": "Fuente",
        "missing": "El significado en este idioma se está añadiendo.",
        "morning_title": "🌅 Adhkar de la mañana",
        "evening_title": "🌙 Adhkar de la tarde",
        "dhikr_word": "Dhikr",
        "translation_note": "Nota: El texto árabe es el original. La traducción es un significado aproximado.",
        "done_morning": "✅ <b>Muy bien.</b>\n\nHas terminado los adhkar de la mañana.",
        "done_evening": "✅ <b>Muy bien.</b>\n\nHas terminado los adhkar de la tarde.",
        "reminder_morning": "🌅 <b>Recordatorio de adhkar de la mañana</b>\n\nEmpieza ahora tus adhkar de la mañana.",
        "reminder_evening": "🌙 <b>Recordatorio de adhkar de la tarde</b>\n\nEmpieza ahora tus adhkar de la tarde.",
        "start_morning_button": "🌅 Empezar adhkar de la mañana",
        "start_evening_button": "🌙 Empezar adhkar de la tarde",
    },
    "tr": {
        "flag": "🇹🇷",
        "name": "Türkçe",
        "label_arabic_text": "Arapça metin",
        "label_meaning": "Türkçe anlamı",
        "label_repeat": "Tekrar",
        "label_source": "Kaynak",
        "missing": "Bu dildeki anlam ekleniyor.",
        "morning_title": "🌅 Sabah zikirleri",
        "evening_title": "🌙 Akşam zikirleri",
        "dhikr_word": "Zikir",
        "translation_note": "Not: Arapça metin asıldır. Çeviri yaklaşık anlamdır.",
        "done_morning": "✅ <b>Güzel.</b>\n\nSabah zikirlerini tamamladınız.",
        "done_evening": "✅ <b>Güzel.</b>\n\nAkşam zikirlerini tamamladınız.",
        "reminder_morning": "🌅 <b>Sabah zikirleri hatırlatması</b>\n\nSabah zikirlerinizi okumaya başlayın.",
        "reminder_evening": "🌙 <b>Akşam zikirleri hatırlatması</b>\n\nAkşam zikirlerinizi okumaya başlayın.",
        "start_morning_button": "🌅 Sabah zikirlerine başla",
        "start_evening_button": "🌙 Akşam zikirlerine başla",
    },
    "id": {
        "flag": "🇮🇩",
        "name": "Indonesia",
        "label_arabic_text": "Teks Arab",
        "label_meaning": "Makna dalam bahasa Indonesia",
        "label_repeat": "Pengulangan",
        "label_source": "Sumber",
        "missing": "Makna dalam bahasa ini sedang ditambahkan.",
        "morning_title": "🌅 Dzikir pagi",
        "evening_title": "🌙 Dzikir petang",
        "dhikr_word": "Dzikir",
        "translation_note": "Catatan: Teks Arab adalah yang asli. Terjemahan adalah makna perkiraan.",
        "done_morning": "✅ <b>Bagus.</b>\n\nAnda telah menyelesaikan dzikir pagi.",
        "done_evening": "✅ <b>Bagus.</b>\n\nAnda telah menyelesaikan dzikir petang.",
        "reminder_morning": "🌅 <b>Pengingat dzikir pagi</b>\n\nMulailah membaca dzikir pagi sekarang.",
        "reminder_evening": "🌙 <b>Pengingat dzikir petang</b>\n\nMulailah membaca dzikir petang sekarang.",
        "start_morning_button": "🌅 Mulai dzikir pagi",
        "start_evening_button": "🌙 Mulai dzikir petang",
    },
    "ur": {
        "flag": "🇺🇷",
        "name": "اردو",
        "label_arabic_text": "عربی متن",
        "label_meaning": "اردو میں معنی",
        "label_repeat": "تکرار",
        "label_source": "ماخذ",
        "missing": "اس زبان میں معنی شامل کیے جا رہے ہیں۔",
        "morning_title": "🌅 صبح کے اذکار",
        "evening_title": "🌙 شام کے اذکار",
        "dhikr_word": "ذکر",
        "translation_note": "نوٹ: عربی متن اصل ہے، ترجمہ صرف تقریبی معنی ہے۔",
        "done_morning": "✅ <b>بہت خوب۔</b>\n\nآپ نے صبح کے اذکار مکمل کر لیے۔",
        "done_evening": "✅ <b>بہت خوب۔</b>\n\nآپ نے شام کے اذکار مکمل کر لیے۔",
        "reminder_morning": "🌅 <b>صبح کے اذکار کی یاد دہانی</b>\n\nاب صبح کے اذکار پڑھنا شروع کریں۔",
        "reminder_evening": "🌙 <b>شام کے اذکار کی یاد دہانی</b>\n\nاب شام کے اذکار پڑھنا شروع کریں۔",
        "start_morning_button": "🌅 صبح کے اذکار شروع کریں",
        "start_evening_button": "🌙 شام کے اذکار شروع کریں",
    },
    "hi": {
        "flag": "🇮🇳",
        "name": "हिन्दी",
        "label_arabic_text": "अरबी पाठ",
        "label_meaning": "हिन्दी में अर्थ",
        "label_repeat": "दोहराव",
        "label_source": "स्रोत",
        "missing": "इस भाषा में अर्थ जोड़ा जा रहा है।",
        "morning_title": "🌅 सुबह के अज़कार",
        "evening_title": "🌙 शाम के अज़कार",
        "dhikr_word": "ज़िक्र",
        "translation_note": "नोट: अरबी पाठ मूल है। अनुवाद केवल अनुमानित अर्थ है।",
        "done_morning": "✅ <b>बहुत अच्छा।</b>\n\nआपने सुबह के अज़कार पूरे कर लिए।",
        "done_evening": "✅ <b>बहुत अच्छा।</b>\n\nआपने शाम के अज़कार पूरे कर लिए।",
        "reminder_morning": "🌅 <b>सुबह के अज़कार की याद दिलाना</b>\n\nअब सुबह के अज़कार पढ़ना शुरू करें।",
        "reminder_evening": "🌙 <b>शाम के अज़कार की याद दिलाना</b>\n\nअब शाम के अज़कार पढ़ना शुरू करें।",
        "start_morning_button": "🌅 सुबह के अज़कार शुरू करें",
        "start_evening_button": "🌙 शाम के अज़कार शुरू करें",
    },
}


REPEAT_TRANSLATIONS = {
    "مرة واحدة": {
        "ar": "مرة واحدة", "en": "Once", "de": "Einmal", "fr": "Une fois", "es": "Una vez",
        "tr": "Bir kez", "id": "Sekali", "ur": "ایک بار", "hi": "एक बार",
    },
    "ثلاث مرات": {
        "ar": "ثلاث مرات", "en": "Three times", "de": "Dreimal", "fr": "Trois fois", "es": "Tres veces",
        "tr": "Üç kez", "id": "Tiga kali", "ur": "تین بار", "hi": "तीन बार",
    },
    "أربع مرات": {
        "ar": "أربع مرات", "en": "Four times", "de": "Viermal", "fr": "Quatre fois", "es": "Cuatro veces",
        "tr": "Dört kez", "id": "Empat kali", "ur": "چار بار", "hi": "चार बार",
    },
    "سبع مرات": {
        "ar": "سبع مرات", "en": "Seven times", "de": "Siebenmal", "fr": "Sept fois", "es": "Siete veces",
        "tr": "Yedi kez", "id": "Tujuh kali", "ur": "سات بار", "hi": "सात बार",
    },
    "عشر مرات": {
        "ar": "عشر مرات", "en": "Ten times", "de": "Zehnmal", "fr": "Dix fois", "es": "Diez veces",
        "tr": "On kez", "id": "Sepuluh kali", "ur": "دس بار", "hi": "दस बार",
    },
    "مائة مرة": {
        "ar": "مائة مرة", "en": "One hundred times", "de": "Hundertmal", "fr": "Cent fois", "es": "Cien veces",
        "tr": "Yüz kez", "id": "Seratus kali", "ur": "سو بار", "hi": "सौ बार",
    },
    "عشر مرات أو مائة مرة": {
        "ar": "عشر مرات أو مائة مرة", "en": "Ten or one hundred times", "de": "Zehnmal oder hundertmal",
        "fr": "Dix ou cent fois", "es": "Diez o cien veces", "tr": "On kez veya yüz kez",
        "id": "Sepuluh atau seratus kali", "ur": "دس بار یا سو بار", "hi": "दस बार या सौ बार",
    },
}


SOURCE_TRANSLATIONS = {
    "من أذكار الصباح": {
        "ar": "من أذكار الصباح", "en": "Morning adhkar", "de": "Morgen-Adhkar",
        "fr": "Adhkâr du matin", "es": "Adhkar de la mañana", "tr": "Sabah zikirleri",
        "id": "Dzikir pagi", "ur": "صبح کے اذکار", "hi": "सुबह के अज़कार",
    },
    "من أذكار المساء": {
        "ar": "من أذكار المساء", "en": "Evening adhkar", "de": "Abend-Adhkar",
        "fr": "Adhkâr du soir", "es": "Adhkar de la tarde", "tr": "Akşam zikirleri",
        "id": "Dzikir petang", "ur": "شام کے اذکار", "hi": "शाम के अज़कार",
    },
    "من أذكار الصباح والمساء": {
        "ar": "من أذكار الصباح والمساء", "en": "Morning and evening adhkar",
        "de": "Morgen- und Abend-Adhkar", "fr": "Adhkâr du matin et du soir",
        "es": "Adhkar de la mañana y de la tarde", "tr": "Sabah ve akşam zikirleri",
        "id": "Dzikir pagi dan petang", "ur": "صبح و شام کے اذکار", "hi": "सुबह और शाम के अज़कार",
    },
    "سيد الاستغفار": {
        "ar": "سيد الاستغفار", "en": "The master supplication for forgiveness",
        "de": "Das umfassende Bittgebet um Vergebung", "fr": "L’invocation maîtresse du pardon",
        "es": "La súplica principal para pedir perdón", "tr": "Bağışlanma duasının en kapsamlısı",
        "id": "Doa utama untuk memohon ampunan", "ur": "استغفار کی جامع دعا", "hi": "क्षमा मांगने की प्रमुख दुआ",
    },
    "من الأذكار": {
        "ar": "من الأذكار", "en": "General dhikr", "de": "Allgemeiner Dhikr", "fr": "Dhikr général",
        "es": "Dhikr general", "tr": "Genel zikir", "id": "Dzikir umum", "ur": "عام ذکر", "hi": "सामान्य ज़िक्र",
    },
    "من الأذكار المشروعة": {
        "ar": "من الأذكار المشروعة", "en": "Legislated remembrance", "de": "Überlieferter Dhikr",
        "fr": "Dhikr rapporté", "es": "Dhikr legislado", "tr": "Meşru zikir",
        "id": "Dzikir yang disyariatkan", "ur": "مشروع ذکر", "hi": "मसनून ज़िक्र",
    },
}


def adhkar_item(ar, repeat_ar, source_ar, meanings):
    return {
        "ar": ar,
        "repeat": {"ar": repeat_ar},
        "source": {"ar": source_ar},
        "meanings": meanings,
    }


MORNING_ADHKAR = [
    adhkar_item(
        "أَصْـبَحْنا وَأَصْـبَحَ المُـلْكُ لله، والحَمْدُ لله، لا إلهَ إلاّ اللهُ وحدَهُ لا شريكَ له، لهُ المُـلْكُ ولهُ الحَمْـد، وهوَ على كلّ شيءٍ قدير.",
        "مرة واحدة",
        "من أذكار الصباح",
        {
            "en": "We have entered the morning, and all dominion belongs to Allah. Praise belongs to Allah. There is no deity worthy of worship except Allah alone, with no partner. His is the dominion and His is the praise, and He has power over all things.",
            "de": "Wir sind in den Morgen eingetreten, und die Herrschaft gehört Allah. Alles Lob gehört Allah. Es gibt keinen anbetungswürdigen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und Ihm gehört das Lob, und Er hat Macht über alle Dinge.",
            "fr": "Nous sommes entrés dans le matin, et toute la royauté appartient à Allah. La louange appartient à Allah. Nul ne mérite d’être adoré sauf Allah, seul, sans associé. À Lui appartient la royauté et la louange, et Il est capable de toute chose.",
            "es": "Hemos llegado a la mañana, y todo dominio pertenece a Allah. La alabanza pertenece a Allah. No hay divinidad digna de adoración excepto Allah, solo, sin asociado. Suyo es el dominio y Suya es la alabanza, y Él tiene poder sobre todas las cosas.",
            "tr": "Sabaha ulaştık ve mülk Allah’ındır. Hamd Allah’adır. Allah’tan başka ibadete layık hiçbir ilah yoktur; O tektir, ortağı yoktur. Mülk O’nundur, hamd O’nadır ve O her şeye güç yetirendir.",
            "id": "Kami memasuki waktu pagi, dan seluruh kerajaan adalah milik Allah. Segala puji bagi Allah. Tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Milik-Nya kerajaan dan milik-Nya segala pujian, dan Dia Mahakuasa atas segala sesuatu.",
            "ur": "ہم نے صبح کی اور بادشاہی اللہ ہی کے لیے ہے۔ تمام تعریف اللہ کے لیے ہے۔ اللہ کے سوا کوئی معبود برحق نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔ بادشاہی اسی کی ہے، تعریف اسی کے لیے ہے، اور وہ ہر چیز پر قادر ہے۔",
            "hi": "हमने सुबह की, और सारी बादशाही अल्लाह ही की है। सारी प्रशंसा अल्लाह के लिए है। अल्लाह के सिवा कोई सच्चा पूज्य नहीं, वह अकेला है, उसका कोई साझी नहीं। उसी की बादशाही है, उसी के लिए प्रशंसा है, और वह हर चीज़ पर शक्ति रखता है।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ بِكَ أَصْـبَحْنا، وَبِكَ أَمْسَيْـنا، وَبِكَ نَحْـيا، وَبِكَ نَمـوتُ، وَإِلَيْكَ النُّـشور.",
        "مرة واحدة",
        "من أذكار الصباح",
        {
            "en": "O Allah, by You we enter the morning, by You we enter the evening, by You we live, by You we die, and to You is the resurrection.",
            "de": "O Allah, durch Dich treten wir in den Morgen ein, durch Dich treten wir in den Abend ein, durch Dich leben wir, durch Dich sterben wir, und zu Dir ist die Auferstehung.",
            "fr": "Ô Allah, c’est par Toi que nous entrons dans le matin, par Toi que nous entrons dans le soir, par Toi que nous vivons, par Toi que nous mourons, et vers Toi sera la résurrection.",
            "es": "Oh Allah, por Ti entramos en la mañana, por Ti entramos en la tarde, por Ti vivimos, por Ti morimos, y hacia Ti será la resurrección.",
            "tr": "Allah’ım, Seninle sabaha ulaştık, Seninle akşama ulaşırız, Seninle yaşarız, Seninle ölürüz ve diriliş Sanadır.",
            "id": "Ya Allah, dengan-Mu kami memasuki pagi, dengan-Mu kami memasuki petang, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu kebangkitan.",
            "ur": "اے اللہ! تیرے ہی ذریعے ہم نے صبح کی، تیرے ہی ذریعے ہم شام کرتے ہیں، تیرے ہی ذریعے ہم جیتے ہیں، تیرے ہی ذریعے ہم مرتے ہیں، اور تیری ہی طرف دوبارہ اٹھایا جانا ہے۔",
            "hi": "ऐ अल्लाह! तेरे ही सहारे हमने सुबह की, तेरे ही सहारे हम शाम करते हैं, तेरे ही सहारे हम जीते हैं, तेरे ही सहारे हम मरते हैं, और तेरी ही ओर उठाया जाना है।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وأنا عَبْـدُك، وأنا على عَهْـدِكَ ووَعْـدِكَ ما استطعتُ، أعوذُ بكَ مِنْ شَرِّ ما صَنَعْت، أبوءُ لكَ بنِعْمَتِكَ عليَّ، وأبوءُ بذَنْـبي، فاغْفِـرْ لي، فإنّهُ لا يَغْفِـرُ الذُّنوبَ إلاّ أنت.",
        "مرة واحدة",
        "سيد الاستغفار",
        {
            "en": "O Allah, You are my Lord. There is no deity worthy of worship except You. You created me and I am Your servant. I remain upon Your covenant and promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.",
            "de": "O Allah, Du bist mein Herr. Es gibt keinen anbetungswürdigen Gott außer Dir. Du hast mich erschaffen und ich bin Dein Diener. Ich halte mich, soweit ich kann, an Deinen Bund und Dein Versprechen. Ich suche Zuflucht bei Dir vor dem Übel dessen, was ich getan habe. Ich erkenne Deine Gnade an mir an und erkenne meine Sünde an, so vergib mir, denn niemand vergibt Sünden außer Dir.",
            "fr": "Ô Allah, Tu es mon Seigneur. Nul ne mérite d’être adoré sauf Toi. Tu m’as créé et je suis Ton serviteur. Je demeure, autant que je le peux, fidèle à Ton engagement et à Ta promesse. Je cherche refuge auprès de Toi contre le mal de ce que j’ai fait. Je reconnais Tes bienfaits envers moi et je reconnais mon péché, alors pardonne-moi, car nul ne pardonne les péchés sauf Toi.",
            "es": "Oh Allah, Tú eres mi Señor. No hay divinidad digna de adoración excepto Tú. Tú me creaste y yo soy Tu siervo. Permanezco, en la medida que puedo, sobre Tu pacto y Tu promesa. Busco refugio en Ti del mal de lo que he hecho. Reconozco Tu favor sobre mí y reconozco mi pecado, así que perdóname, pues nadie perdona los pecados excepto Tú.",
            "tr": "Allah’ım, Sen benim Rabbimsin. Senden başka ibadete layık ilah yoktur. Beni Sen yarattın ve ben Senin kulunum. Gücüm yettiğince Senin ahdin ve vaadin üzereyim. Yaptıklarımın şerrinden Sana sığınırım. Bana verdiğin nimetleri kabul ederim, günahımı da kabul ederim. Beni bağışla; çünkü günahları Senden başka bağışlayacak yoktur.",
            "id": "Ya Allah, Engkau adalah Tuhanku. Tidak ada sesembahan yang berhak disembah selain Engkau. Engkau menciptakanku dan aku adalah hamba-Mu. Aku tetap berada di atas janji dan perjanjian-Mu semampuku. Aku berlindung kepada-Mu dari keburukan perbuatanku. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku, karena tidak ada yang mengampuni dosa selain Engkau.",
            "ur": "اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود برحق نہیں۔ تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں۔ میں اپنی استطاعت کے مطابق تیرے عہد اور وعدے پر قائم ہوں۔ میں اپنے کیے کے شر سے تیری پناہ چاہتا ہوں۔ میں اپنے اوپر تیری نعمت کا اقرار کرتا ہوں اور اپنے گناہ کا بھی اقرار کرتا ہوں، پس مجھے بخش دے، کیونکہ تیرے سوا کوئی گناہوں کو نہیں بخشتا۔",
            "hi": "ऐ अल्लाह! तू मेरा रब है। तेरे सिवा कोई सच्चा पूज्य नहीं। तूने मुझे पैदा किया और मैं तेरा बंदा हूँ। मैं अपनी क्षमता के अनुसार तेरे वचन और वादे पर कायम हूँ। मैं अपने किए हुए कर्मों की बुराई से तेरी पनाह चाहता हूँ। मैं अपने ऊपर तेरी नेमत को स्वीकार करता हूँ और अपने पाप को भी स्वीकार करता हूँ, इसलिए मुझे क्षमा कर दे, क्योंकि तेरे सिवा कोई पापों को क्षमा नहीं करता।",
        },
    ),
    adhkar_item(
        "رَضيتُ باللهِ ربًّا، وبالإسلامِ دينًا، وبمحمّدٍ ﷺ نبيًّا.",
        "ثلاث مرات",
        "من أذكار الصباح والمساء",
        {
            "en": "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad ﷺ as my Prophet.",
            "de": "Ich bin zufrieden mit Allah als meinem Herrn, mit dem Islam als meiner Religion und mit Muhammad ﷺ als meinem Propheten.",
            "fr": "J’agrée Allah comme Seigneur, l’Islam comme religion et Muhammad ﷺ comme Prophète.",
            "es": "Estoy complacido con Allah como mi Señor, con el Islam como mi religión y con Muhammad ﷺ como mi Profeta.",
            "tr": "Rab olarak Allah’tan, din olarak İslam’dan ve peygamber olarak Muhammed’den ﷺ razıyım.",
            "id": "Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai Nabiku.",
            "ur": "میں اللہ کے رب ہونے، اسلام کے دین ہونے، اور محمد ﷺ کے نبی ہونے پر راضی ہوں۔",
            "hi": "मैं अल्लाह को अपना रब, इस्लाम को अपना धर्म और मुहम्मद ﷺ को अपना नबी मानकर राज़ी हूँ।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ إنّي أَصْبَحْتُ أُشْهِدُكَ، وأُشْهِدُ حَمَلَةَ عَرْشِكَ، ومَلائِكَتَكَ، وجميعَ خَلْقِكَ، أنّكَ أنتَ اللهُ لا إلهَ إلاّ أنتَ وحدَكَ لا شريكَ لك، وأنّ محمّدًا عبدُكَ ورسولُك.",
        "أربع مرات",
        "من أذكار الصباح",
        {
            "en": "O Allah, I have entered the morning calling You to witness, and calling the bearers of Your Throne, Your angels, and all Your creation to witness, that You are Allah; there is no deity worthy of worship except You alone with no partner, and that Muhammad is Your servant and Messenger.",
            "de": "O Allah, ich bin in den Morgen eingetreten und rufe Dich, die Träger Deines Thrones, Deine Engel und Deine gesamte Schöpfung als Zeugen an, dass Du Allah bist; es gibt keinen anbetungswürdigen Gott außer Dir allein, ohne Partner, und dass Muhammad Dein Diener und Gesandter ist.",
            "fr": "Ô Allah, me voici au matin, je Te prends à témoin, ainsi que les porteurs de Ton Trône, Tes anges et toute Ta création, que Tu es Allah, nul ne mérite d’être adoré sauf Toi, seul, sans associé, et que Muhammad est Ton serviteur et Messager.",
            "es": "Oh Allah, he llegado a la mañana y Te tomo como testigo, junto con los portadores de Tu Trono, Tus ángeles y toda Tu creación, de que Tú eres Allah; no hay divinidad digna de adoración excepto Tú, solo, sin asociado, y que Muhammad es Tu siervo y Mensajero.",
            "tr": "Allah’ım, sabaha ulaştım ve Seni, Arşını taşıyanları, meleklerini ve bütün yaratılmışlarını şahit tutuyorum ki Sen Allah’sın; Senden başka ibadete layık ilah yoktur, Sen teksin ve ortağın yoktur; Muhammed de Senin kulun ve elçindir.",
            "id": "Ya Allah, aku memasuki pagi dengan menjadikan-Mu sebagai saksi, juga para pemikul Arsy-Mu, para malaikat-Mu, dan seluruh makhluk-Mu, bahwa Engkau adalah Allah; tidak ada sesembahan yang berhak disembah selain Engkau semata, tidak ada sekutu bagi-Mu, dan Muhammad adalah hamba dan Rasul-Mu.",
            "ur": "اے اللہ! میں نے صبح کی اس حال میں کہ میں تجھے، تیرے عرش کے حاملین کو، تیرے فرشتوں کو اور تیری تمام مخلوق کو گواہ بناتا ہوں کہ تو ہی اللہ ہے، تیرے سوا کوئی معبود برحق نہیں، تو اکیلا ہے، تیرا کوئی شریک نہیں، اور محمد تیرے بندے اور رسول ہیں۔",
            "hi": "ऐ अल्लाह! मैंने सुबह की और तुझे, तेरे अर्श को उठाने वालों को, तेरे फ़रिश्तों को और तेरी सारी मख़लूक़ को गवाह बनाता हूँ कि तू ही अल्लाह है; तेरे सिवा कोई सच्चा पूज्य नहीं, तू अकेला है, तेरा कोई साझी नहीं, और मुहम्मद तेरे बंदे और रसूल हैं।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ ما أَصْبَحَ بي مِنْ نِعْمَةٍ أو بأَحَدٍ مِنْ خَلْقِكَ، فَمِنْكَ وحدَكَ لا شريكَ لك، فَلَكَ الحمدُ ولكَ الشُّكر.",
        "مرة واحدة",
        "من أذكار الصباح",
        {
            "en": "O Allah, whatever blessing has come to me or to any of Your creation this morning is from You alone, with no partner. To You belongs all praise and all thanks.",
            "de": "O Allah, jede Gnade, die mich oder eines Deiner Geschöpfe an diesem Morgen erreicht hat, ist von Dir allein, ohne Partner. Dir gebührt alles Lob und aller Dank.",
            "fr": "Ô Allah, tout bienfait qui m’a atteint ce matin, ou qui a atteint l’une de Tes créatures, vient de Toi seul, sans associé. À Toi la louange et à Toi la gratitude.",
            "es": "Oh Allah, cualquier bendición que me haya llegado esta mañana, o que haya llegado a cualquiera de Tus criaturas, viene solo de Ti, sin asociado. A Ti pertenece toda alabanza y todo agradecimiento.",
            "tr": "Allah’ım, bu sabah bana veya yaratıklarından birine ulaşan her nimet yalnızca Sendendir, ortağın yoktur. Hamd de şükür de Sanadır.",
            "id": "Ya Allah, nikmat apa pun yang sampai kepadaku atau kepada salah satu makhluk-Mu pada pagi ini, semuanya berasal dari-Mu semata, tidak ada sekutu bagi-Mu. Segala puji dan syukur bagi-Mu.",
            "ur": "اے اللہ! جو بھی نعمت مجھ پر یا تیری کسی مخلوق پر اس صبح آئی ہے، وہ صرف تیری طرف سے ہے، تیرا کوئی شریک نہیں۔ پس تمام تعریف اور شکر تیرے ہی لیے ہے۔",
            "hi": "ऐ अल्लाह! जो भी नेमत इस सुबह मुझ पर या तेरी किसी मख़लूक़ पर आई है, वह केवल तेरी ओर से है, तेरा कोई साझी नहीं। इसलिए सारी प्रशंसा और शुक्र तेरे ही लिए है।",
        },
    ),
    adhkar_item(
        "حَسْبِيَ اللهُ لا إلهَ إلاّ هو، عليهِ توكّلتُ، وهوَ ربُّ العرشِ العظيم.",
        "سبع مرات",
        "من أذكار الصباح والمساء",
        {
            "en": "Allah is sufficient for me. There is no deity worthy of worship except Him. Upon Him I rely, and He is the Lord of the Mighty Throne.",
            "de": "Allah genügt mir. Es gibt keinen anbetungswürdigen Gott außer Ihm. Auf Ihn vertraue ich, und Er ist der Herr des gewaltigen Thrones.",
            "fr": "Allah me suffit. Nul ne mérite d’être adoré sauf Lui. C’est en Lui que je place ma confiance, et Il est le Seigneur du Trône immense.",
            "es": "Allah me basta. No hay divinidad digna de adoración excepto Él. En Él confío, y Él es el Señor del Trono inmenso.",
            "tr": "Allah bana yeter. O’ndan başka ibadete layık ilah yoktur. O’na tevekkül ettim. O, büyük Arş’ın Rabbidir.",
            "id": "Cukuplah Allah bagiku. Tidak ada sesembahan yang berhak disembah selain Dia. Kepada-Nya aku bertawakal, dan Dia adalah Tuhan Arsy yang agung.",
            "ur": "مجھے اللہ کافی ہے۔ اس کے سوا کوئی معبود برحق نہیں۔ میں نے اسی پر بھروسہ کیا، اور وہ عرش عظیم کا رب ہے۔",
            "hi": "मुझे अल्लाह काफ़ी है। उसके सिवा कोई सच्चा पूज्य नहीं। मैंने उसी पर भरोसा किया, और वह महान अर्श का रब है।",
        },
    ),
    adhkar_item(
        "بِسْمِ اللهِ الذي لا يَضُرُّ مع اسمِهِ شيءٌ في الأرضِ ولا في السماءِ، وهوَ السميعُ العليم.",
        "ثلاث مرات",
        "من أذكار الصباح والمساء",
        {
            "en": "In the name of Allah, with whose name nothing on earth or in the heavens can cause harm, and He is the All-Hearing, the All-Knowing.",
            "de": "Im Namen Allahs, mit dessen Namen nichts auf der Erde und nichts im Himmel Schaden zufügen kann. Er ist der Allhörende, der Allwissende.",
            "fr": "Au nom d’Allah, avec le nom duquel rien ne peut nuire sur terre ni dans le ciel. Il est l’Audient, l’Omniscient.",
            "es": "En el nombre de Allah, con cuyo nombre nada en la tierra ni en el cielo puede causar daño. Él es el que todo lo oye, el que todo lo sabe.",
            "tr": "Allah’ın adıyla; O’nun adıyla yerde ve gökte hiçbir şey zarar veremez. O, her şeyi işiten ve her şeyi bilendir.",
            "id": "Dengan nama Allah, yang dengan nama-Nya tidak ada sesuatu pun di bumi maupun di langit yang dapat membahayakan. Dia Maha Mendengar lagi Maha Mengetahui.",
            "ur": "اللہ کے نام سے، جس کے نام کے ساتھ زمین و آسمان کی کوئی چیز نقصان نہیں پہنچا سکتی، اور وہ خوب سننے والا، خوب جاننے والا ہے۔",
            "hi": "अल्लाह के नाम से, जिसके नाम के साथ धरती और आकाश में कोई चीज़ नुकसान नहीं पहुँचा सकती। वह सब सुनने वाला, सब जानने वाला है।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ عافِني في بَدَني، اللّهـمَّ عافِني في سَمْعي، اللّهـمَّ عافِني في بَصَري، لا إلهَ إلاّ أنت.",
        "ثلاث مرات",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, grant me well-being in my body. O Allah, grant me well-being in my hearing. O Allah, grant me well-being in my sight. There is no deity worthy of worship except You.",
            "de": "O Allah, schenke mir Wohlergehen in meinem Körper. O Allah, schenke mir Wohlergehen in meinem Gehör. O Allah, schenke mir Wohlergehen in meinem Sehvermögen. Es gibt keinen anbetungswürdigen Gott außer Dir.",
            "fr": "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nul ne mérite d’être adoré sauf Toi.",
            "es": "Oh Allah, concédeme bienestar en mi cuerpo. Oh Allah, concédeme bienestar en mi oído. Oh Allah, concédeme bienestar en mi vista. No hay divinidad digna de adoración excepto Tú.",
            "tr": "Allah’ım, bedenime afiyet ver. Allah’ım, işitmeme afiyet ver. Allah’ım, görmeme afiyet ver. Senden başka ibadete layık ilah yoktur.",
            "id": "Ya Allah, berilah kesehatan pada tubuhku. Ya Allah, berilah kesehatan pada pendengaranku. Ya Allah, berilah kesehatan pada penglihatanku. Tidak ada sesembahan yang berhak disembah selain Engkau.",
            "ur": "اے اللہ! میرے جسم میں عافیت دے۔ اے اللہ! میری سماعت میں عافیت دے۔ اے اللہ! میری بینائی میں عافیت دے۔ تیرے سوا کوئی معبود برحق نہیں۔",
            "hi": "ऐ अल्लाह! मेरे शरीर में आफ़ियत दे। ऐ अल्लाह! मेरी सुनने की शक्ति में आफ़ियत दे। ऐ अल्लाह! मेरी देखने की शक्ति में आफ़ियत दे। तेरे सिवा कोई सच्चा पूज्य नहीं।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ إنّي أعوذُ بكَ مِنَ الكُفْرِ والفَقْر، وأعوذُ بكَ مِنْ عذابِ القَبْر، لا إلهَ إلاّ أنت.",
        "ثلاث مرات",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. There is no deity worthy of worship except You.",
            "de": "O Allah, ich suche Zuflucht bei Dir vor Unglauben und Armut, und ich suche Zuflucht bei Dir vor der Strafe des Grabes. Es gibt keinen anbetungswürdigen Gott außer Dir.",
            "fr": "Ô Allah, je cherche refuge auprès de Toi contre la mécréance et la pauvreté, et je cherche refuge auprès de Toi contre le châtiment de la tombe. Nul ne mérite d’être adoré sauf Toi.",
            "es": "Oh Allah, busco refugio en Ti de la incredulidad y la pobreza, y busco refugio en Ti del castigo de la tumba. No hay divinidad digna de adoración excepto Tú.",
            "tr": "Allah’ım, küfürden ve fakirlikten Sana sığınırım. Kabir azabından da Sana sığınırım. Senden başka ibadete layık ilah yoktur.",
            "id": "Ya Allah, aku berlindung kepada-Mu dari kekufuran dan kemiskinan, dan aku berlindung kepada-Mu dari azab kubur. Tidak ada sesembahan yang berhak disembah selain Engkau.",
            "ur": "اے اللہ! میں کفر اور فقر سے تیری پناہ چاہتا ہوں، اور قبر کے عذاب سے تیری پناہ چاہتا ہوں۔ تیرے سوا کوئی معبود برحق نہیں۔",
            "hi": "ऐ अल्लाह! मैं कुफ़्र और निर्धनता से तेरी पनाह चाहता हूँ, और क़ब्र के अज़ाब से तेरी पनाह चाहता हूँ। तेरे सिवा कोई सच्चा पूज्य नहीं।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ إنّي أسألُكَ العفوَ والعافيةَ في الدنيا والآخرة.",
        "مرة واحدة",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
            "de": "O Allah, ich bitte Dich um Vergebung und Wohlergehen im Diesseits und im Jenseits.",
            "fr": "Ô Allah, je Te demande le pardon et le bien-être dans ce monde et dans l’au-delà.",
            "es": "Oh Allah, Te pido perdón y bienestar en este mundo y en la Otra Vida.",
            "tr": "Allah’ım, Senden dünyada ve ahirette af ve afiyet isterim.",
            "id": "Ya Allah, aku memohon kepada-Mu ampunan dan keselamatan di dunia dan akhirat.",
            "ur": "اے اللہ! میں تجھ سے دنیا اور آخرت میں عفو اور عافیت کا سوال کرتا ہوں۔",
            "hi": "ऐ अल्लाह! मैं तुझसे दुनिया और आख़िरत में क्षमा और आफ़ियत मांगता हूँ।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ إنّي أسألُكَ العفوَ والعافيةَ في ديني ودنيايَ وأهلي ومالي.",
        "مرة واحدة",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, I ask You for pardon and well-being in my religion, my worldly life, my family, and my wealth.",
            "de": "O Allah, ich bitte Dich um Vergebung und Wohlergehen in meiner Religion, meinem weltlichen Leben, meiner Familie und meinem Besitz.",
            "fr": "Ô Allah, je Te demande le pardon et le bien-être dans ma religion, ma vie d’ici-bas, ma famille et mes biens.",
            "es": "Oh Allah, Te pido perdón y bienestar en mi religión, mi vida mundanal, mi familia y mis bienes.",
            "tr": "Allah’ım, dinimde, dünyamda, ailemde ve malımda Senden af ve afiyet isterim.",
            "id": "Ya Allah, aku memohon kepada-Mu ampunan dan keselamatan dalam agamaku, duniaku, keluargaku, dan hartaku.",
            "ur": "اے اللہ! میں تجھ سے اپنے دین، دنیا، اہل و عیال اور مال میں عفو اور عافیت کا سوال کرتا ہوں۔",
            "hi": "ऐ अल्लाह! मैं तुझसे अपने धर्म, अपनी दुनिया, अपने परिवार और अपने माल में क्षमा और आफ़ियत मांगता हूँ।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ استُرْ عوراتي، وآمِنْ رَوْعاتي.",
        "مرة واحدة",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, conceal my faults and calm my fears.",
            "de": "O Allah, bedecke meine Fehler und beruhige meine Ängste.",
            "fr": "Ô Allah, couvre mes défauts et apaise mes craintes.",
            "es": "Oh Allah, cubre mis faltas y calma mis temores.",
            "tr": "Allah’ım, kusurlarımı ört ve korkularımı gider.",
            "id": "Ya Allah, tutupilah kekuranganku dan tenangkanlah ketakutanku.",
            "ur": "اے اللہ! میری پردہ پوشی فرما اور میرے خوف کو امن میں بدل دے۔",
            "hi": "ऐ अल्लाह! मेरी कमियों पर पर्दा डाल और मेरे डर को शांति में बदल दे।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ احفظني مِنْ بينِ يديَّ، ومِنْ خَلْفي، وعن يميني، وعن شمالي، ومِنْ فوقي، وأعوذُ بعظمتِكَ أن أُغتالَ مِنْ تحتي.",
        "مرة واحدة",
        "من أذكار الصباح والمساء",
        {
            "en": "O Allah, protect me from in front of me, from behind me, from my right, from my left, and from above me. I seek refuge in Your greatness from being taken unaware from beneath me.",
            "de": "O Allah, beschütze mich von vorne, von hinten, von rechts, von links und von oben. Ich suche Zuflucht bei Deiner Größe davor, von unten unerwartet getroffen zu werden.",
            "fr": "Ô Allah, protège-moi devant moi, derrière moi, à ma droite, à ma gauche et au-dessus de moi. Je cherche refuge par Ta grandeur contre le fait d’être atteint par-dessous.",
            "es": "Oh Allah, protégeme por delante, por detrás, por mi derecha, por mi izquierda y por encima de mí. Busco refugio en Tu grandeza de ser sorprendido desde debajo de mí.",
            "tr": "Allah’ım, beni önümden, arkamdan, sağımdan, solumdan ve üstümden koru. Altımdan ansızın yakalanmaktan Senin azametine sığınırım.",
            "id": "Ya Allah, lindungilah aku dari depan, belakang, kanan, kiri, dan atasku. Aku berlindung dengan keagungan-Mu agar tidak diserang dari bawahku.",
            "ur": "اے اللہ! میرے آگے، پیچھے، دائیں، بائیں اور اوپر سے میری حفاظت فرما، اور میں تیری عظمت کے ذریعے پناہ چاہتا ہوں کہ نیچے سے اچانک پکڑا جاؤں۔",
            "hi": "ऐ अल्लाह! मेरे आगे, पीछे, दाएँ, बाएँ और ऊपर से मेरी रक्षा कर। और मैं तेरी महानता के साथ पनाह चाहता हूँ कि मुझे नीचे से अचानक पकड़ लिया जाए।",
        },
    ),
    adhkar_item(
        "يا حيُّ يا قيّومُ، برحمتِكَ أستغيث، أصلِحْ لي شأني كلَّه، ولا تَكِلْني إلى نفسي طَرْفَةَ عين.",
        "مرة واحدة",
        "من أذكار الصباح والمساء",
        {
            "en": "O Ever-Living, O Sustainer, by Your mercy I seek help. Rectify all of my affairs and do not leave me to myself even for the blink of an eye.",
            "de": "O Ewig-Lebendiger, O Erhalter, durch Deine Barmherzigkeit suche ich Hilfe. Verbessere all meine Angelegenheiten und überlasse mich mir selbst nicht einmal für einen Augenblick.",
            "fr": "Ô Vivant, ô Celui qui subsiste par Lui-même et fait subsister toute chose, par Ta miséricorde je cherche secours. Réforme toutes mes affaires et ne me laisse pas à moi-même, même le temps d’un clin d’œil.",
            "es": "Oh Viviente, oh Sustentador, por Tu misericordia busco ayuda. Rectifica todos mis asuntos y no me dejes a cargo de mí mismo ni por un parpadeo.",
            "tr": "Ey Hayy, ey Kayyûm! Rahmetinle yardım isterim. Bütün işlerimi düzelt ve beni göz açıp kapayıncaya kadar bile nefsime bırakma.",
            "id": "Wahai Yang Mahahidup, wahai Yang Maha Mengurus, dengan rahmat-Mu aku memohon pertolongan. Perbaikilah seluruh urusanku dan jangan Engkau serahkan aku kepada diriku sendiri walau sekejap mata.",
            "ur": "اے ہمیشہ زندہ، اے قائم رکھنے والے! میں تیری رحمت کے ذریعے مدد چاہتا ہوں۔ میرے تمام معاملات درست فرما اور مجھے پلک جھپکنے کے برابر بھی میرے نفس کے حوالے نہ کر۔",
            "hi": "ऐ हमेशा ज़िंदा, ऐ सबको संभालने वाले! मैं तेरी रहमत से मदद चाहता हूँ। मेरे सभी मामलों को सुधार दे और मुझे पलक झपकने भर भी मेरे अपने हवाले न कर।",
        },
    ),
    adhkar_item(
        "أَصْبَحْنا على فِطْرَةِ الإسلام، وعلى كلمةِ الإخلاص، وعلى دينِ نبيّنا محمدٍ ﷺ، وعلى مِلّةِ أبينا إبراهيمَ حنيفًا مسلمًا وما كانَ مِنَ المشركين.",
        "مرة واحدة",
        "من أذكار الصباح",
        {
            "en": "We have entered the morning upon the natural way of Islam, the word of sincerity, the religion of our Prophet Muhammad ﷺ, and the way of our father Ibrahim, who was upright and Muslim and was not among the polytheists.",
            "de": "Wir sind in den Morgen eingetreten auf der natürlichen Veranlagung des Islam, auf dem Wort der Aufrichtigkeit, auf der Religion unseres Propheten Muhammad ﷺ und auf dem Weg unseres Vaters Ibrahim, der aufrichtig und Muslim war und nicht zu den Götzendienern gehörte.",
            "fr": "Nous sommes entrés dans le matin sur la nature saine de l’Islam, sur la parole de sincérité, sur la religion de notre Prophète Muhammad ﷺ et sur la voie de notre père Ibrahim, droit, soumis à Allah et non parmi les associateurs.",
            "es": "Hemos llegado a la mañana sobre la naturaleza del Islam, sobre la palabra de sinceridad, sobre la religión de nuestro Profeta Muhammad ﷺ y sobre la vía de nuestro padre Ibrahim, recto, musulmán y no de los idólatras.",
            "tr": "İslam fıtratı, ihlas kelimesi, Peygamberimiz Muhammed’in ﷺ dini ve babamız İbrahim’in dosdoğru ve Müslüman olan yolu üzere sabaha ulaştık; o müşriklerden değildi.",
            "id": "Kami memasuki pagi di atas fitrah Islam, kalimat ikhlas, agama Nabi kami Muhammad ﷺ, dan ajaran bapak kami Ibrahim yang lurus dan berserah diri, dan ia bukan termasuk orang-orang musyrik.",
            "ur": "ہم نے اسلام کی فطرت، اخلاص کے کلمے، اپنے نبی محمد ﷺ کے دین، اور اپنے باپ ابراہیم کی ملت پر صبح کی، جو یکسو مسلمان تھے اور مشرکوں میں سے نہ تھے۔",
            "hi": "हमने इस्लाम की फ़ितरत, इख़लास के कलिमे, अपने नबी मुहम्मद ﷺ के धर्म और अपने पिता इब्राहीम के सीधे और मुस्लिम मार्ग पर सुबह की, और वे मुश्रिकों में से नहीं थे।",
        },
    ),
    adhkar_item(
        "سُبْحانَ اللهِ وبحمدِه.",
        "مائة مرة",
        "من أذكار الصباح والمساء",
        {
            "en": "Glory and praise be to Allah.",
            "de": "Preis sei Allah und Lob sei Ihm.",
            "fr": "Gloire et louange à Allah.",
            "es": "Gloria y alabanza sean para Allah.",
            "tr": "Allah’ı tesbih ederim ve O’na hamd ederim.",
            "id": "Mahasuci Allah dan segala puji bagi-Nya.",
            "ur": "اللہ پاک ہے اور اسی کے لیے تعریف ہے۔",
            "hi": "अल्लाह पाक है और सारी प्रशंसा उसी के लिए है।",
        },
    ),
    adhkar_item(
        "لا إلهَ إلاّ اللهُ وحدَهُ لا شريكَ له، لهُ الملكُ ولهُ الحمدُ، وهوَ على كلّ شيءٍ قدير.",
        "عشر مرات أو مائة مرة",
        "من أذكار الصباح والمساء",
        {
            "en": "There is no deity worthy of worship except Allah alone, with no partner. His is the dominion and His is the praise, and He has power over all things.",
            "de": "Es gibt keinen anbetungswürdigen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und Ihm gehört das Lob, und Er hat Macht über alle Dinge.",
            "fr": "Nul ne mérite d’être adoré sauf Allah, seul, sans associé. À Lui appartient la royauté et la louange, et Il est capable de toute chose.",
            "es": "No hay divinidad digna de adoración excepto Allah, solo, sin asociado. Suyo es el dominio y Suya es la alabanza, y Él tiene poder sobre todas las cosas.",
            "tr": "Allah’tan başka ibadete layık hiçbir ilah yoktur; O tektir, ortağı yoktur. Mülk O’nundur, hamd O’nadır ve O her şeye güç yetirendir.",
            "id": "Tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Milik-Nya kerajaan dan milik-Nya segala pujian, dan Dia Mahakuasa atas segala sesuatu.",
            "ur": "اللہ کے سوا کوئی معبود برحق نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔ بادشاہی اسی کی ہے، تعریف اسی کے لیے ہے، اور وہ ہر چیز پر قادر ہے۔",
            "hi": "अल्लाह के सिवा कोई सच्चा पूज्य नहीं, वह अकेला है, उसका कोई साझी नहीं। उसी की बादशाही है, उसी के लिए प्रशंसा है, और वह हर चीज़ पर शक्ति रखता है।",
        },
    ),
    adhkar_item(
        "أستغفرُ اللهَ وأتوبُ إليه.",
        "مائة مرة",
        "من الأذكار",
        {
            "en": "I seek Allah’s forgiveness and repent to Him.",
            "de": "Ich bitte Allah um Vergebung und kehre reumütig zu Ihm zurück.",
            "fr": "Je demande pardon à Allah et je me repens à Lui.",
            "es": "Pido perdón a Allah y me arrepiento ante Él.",
            "tr": "Allah’tan bağışlanma dilerim ve O’na tövbe ederim.",
            "id": "Aku memohon ampun kepada Allah dan bertaubat kepada-Nya.",
            "ur": "میں اللہ سے بخشش طلب کرتا ہوں اور اسی کی طرف توبہ کرتا ہوں۔",
            "hi": "मैं अल्लाह से क्षमा मांगता हूँ और उसी की ओर तौबा करता हूँ।",
        },
    ),
    adhkar_item(
        "اللّهـمَّ صلِّ وسلّمْ على نبيّنا محمد.",
        "عشر مرات",
        "من الأذكار المشروعة",
        {
            "en": "O Allah, send prayers and peace upon our Prophet Muhammad.",
            "de": "O Allah, sende Segen und Frieden auf unseren Propheten Muhammad.",
            "fr": "Ô Allah, accorde Tes prières et Ta paix à notre Prophète Muhammad.",
            "es": "Oh Allah, concede bendiciones y paz a nuestro Profeta Muhammad.",
            "tr": "Allah’ım, Peygamberimiz Muhammed’e salât ve selâm eyle.",
            "id": "Ya Allah, limpahkan salawat dan salam kepada Nabi kami Muhammad.",
            "ur": "اے اللہ! ہمارے نبی محمد پر درود و سلام بھیج۔",
            "hi": "ऐ अल्लाह! हमारे नबी मुहम्मद पर दुरूद और सलाम भेज।",
        },
    ),
]


EVENING_ADHKAR = [item.copy() for item in MORNING_ADHKAR]

EVENING_ADHKAR[0] = adhkar_item(
    "أَمْسَيْنا وأَمْسَى المُـلْكُ لله، والحَمْدُ لله، لا إلهَ إلاّ اللهُ وحدَهُ لا شريكَ له، لهُ المُـلْكُ ولهُ الحَمْـد، وهوَ على كلّ شيءٍ قدير.",
    "مرة واحدة",
    "من أذكار المساء",
    {
        "en": "We have entered the evening, and all dominion belongs to Allah. Praise belongs to Allah. There is no deity worthy of worship except Allah alone, with no partner. His is the dominion and His is the praise, and He has power over all things.",
        "de": "Wir sind in den Abend eingetreten, und die Herrschaft gehört Allah. Alles Lob gehört Allah. Es gibt keinen anbetungswürdigen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und Ihm gehört das Lob, und Er hat Macht über alle Dinge.",
        "fr": "Nous sommes entrés dans le soir, et toute la royauté appartient à Allah. La louange appartient à Allah. Nul ne mérite d’être adoré sauf Allah, seul, sans associé. À Lui appartient la royauté et la louange, et Il est capable de toute chose.",
        "es": "Hemos llegado a la tarde, y todo dominio pertenece a Allah. La alabanza pertenece a Allah. No hay divinidad digna de adoración excepto Allah, solo, sin asociado. Suyo es el dominio y Suya es la alabanza, y Él tiene poder sobre todas las cosas.",
        "tr": "Akşama ulaştık ve mülk Allah’ındır. Hamd Allah’adır. Allah’tan başka ibadete layık hiçbir ilah yoktur; O tektir, ortağı yoktur. Mülk O’nundur, hamd O’nadır ve O her şeye güç yetirendir.",
        "id": "Kami memasuki waktu petang, dan seluruh kerajaan adalah milik Allah. Segala puji bagi Allah. Tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Milik-Nya kerajaan dan milik-Nya segala pujian, dan Dia Mahakuasa atas segala sesuatu.",
        "ur": "ہم نے شام کی اور بادشاہی اللہ ہی کے لیے ہے۔ تمام تعریف اللہ کے لیے ہے۔ اللہ کے سوا کوئی معبود برحق نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔ بادشاہی اسی کی ہے، تعریف اسی کے لیے ہے، اور وہ ہر چیز پر قادر ہے۔",
        "hi": "हमने शाम की, और सारी बादशाही अल्लाह ही की है। सारी प्रशंसा अल्लाह के लिए है। अल्लाह के सिवा कोई सच्चा पूज्य नहीं, वह अकेला है, उसका कोई साझी नहीं। उसी की बादशाही है, उसी के लिए प्रशंसा है, और वह हर चीज़ पर शक्ति रखता है।",
    },
)

EVENING_ADHKAR[1] = adhkar_item(
    "اللّهـمَّ بِكَ أَمْسَيْنا، وبِكَ أَصْبَحْنا، وبِكَ نَحْيا، وبِكَ نَموتُ، وإليكَ المصير.",
    "مرة واحدة",
    "من أذكار المساء",
    {
        "en": "O Allah, by You we enter the evening, by You we enter the morning, by You we live, by You we die, and to You is the return.",
        "de": "O Allah, durch Dich treten wir in den Abend ein, durch Dich treten wir in den Morgen ein, durch Dich leben wir, durch Dich sterben wir, und zu Dir ist die Rückkehr.",
        "fr": "Ô Allah, c’est par Toi que nous entrons dans le soir, par Toi que nous entrons dans le matin, par Toi que nous vivons, par Toi que nous mourons, et vers Toi est le retour.",
        "es": "Oh Allah, por Ti entramos en la tarde, por Ti entramos en la mañana, por Ti vivimos, por Ti morimos, y hacia Ti es el retorno.",
        "tr": "Allah’ım, Seninle akşama ulaştık, Seninle sabaha ulaşırız, Seninle yaşarız, Seninle ölürüz ve dönüş Sanadır.",
        "id": "Ya Allah, dengan-Mu kami memasuki petang, dengan-Mu kami memasuki pagi, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu tempat kembali.",
        "ur": "اے اللہ! تیرے ہی ذریعے ہم نے شام کی، تیرے ہی ذریعے ہم صبح کرتے ہیں، تیرے ہی ذریعے ہم جیتے ہیں، تیرے ہی ذریعے ہم مرتے ہیں، اور تیری ہی طرف لوٹنا ہے۔",
        "hi": "ऐ अल्लाह! तेरे ही सहारे हमने शाम की, तेरे ही सहारे हम सुबह करते हैं, तेरे ही सहारे हम जीते हैं, तेरे ही सहारे हम मरते हैं, और तेरी ही ओर लौटना है।",
    },
)

EVENING_ADHKAR[4] = adhkar_item(
    "اللّهـمَّ إنّي أَمْسَيْتُ أُشْهِدُكَ، وأُشْهِدُ حَمَلَةَ عَرْشِكَ، ومَلائِكَتَكَ، وجميعَ خَلْقِكَ، أنّكَ أنتَ اللهُ لا إلهَ إلاّ أنتَ وحدَكَ لا شريكَ لك، وأنّ محمّدًا عبدُكَ ورسولُك.",
    "أربع مرات",
    "من أذكار المساء",
    {
        "en": "O Allah, I have entered the evening calling You to witness, and calling the bearers of Your Throne, Your angels, and all Your creation to witness, that You are Allah; there is no deity worthy of worship except You alone with no partner, and that Muhammad is Your servant and Messenger.",
        "de": "O Allah, ich bin in den Abend eingetreten und rufe Dich, die Träger Deines Thrones, Deine Engel und Deine gesamte Schöpfung als Zeugen an, dass Du Allah bist; es gibt keinen anbetungswürdigen Gott außer Dir allein, ohne Partner, und dass Muhammad Dein Diener und Gesandter ist.",
        "fr": "Ô Allah, me voici au soir, je Te prends à témoin, ainsi que les porteurs de Ton Trône, Tes anges et toute Ta création, que Tu es Allah, nul ne mérite d’être adoré sauf Toi, seul, sans associé, et que Muhammad est Ton serviteur et Messager.",
        "es": "Oh Allah, he llegado a la tarde y Te tomo como testigo, junto con los portadores de Tu Trono, Tus ángeles y toda Tu creación, de que Tú eres Allah; no hay divinidad digna de adoración excepto Tú, solo, sin asociado, y que Muhammad es Tu siervo y Mensajero.",
        "tr": "Allah’ım, akşama ulaştım ve Seni, Arşını taşıyanları, meleklerini ve bütün yaratılmışlarını şahit tutuyorum ki Sen Allah’sın; Senden başka ibadete layık ilah yoktur, Sen teksin ve ortağın yoktur; Muhammed de Senin kulun ve elçindir.",
        "id": "Ya Allah, aku memasuki petang dengan menjadikan-Mu sebagai saksi, juga para pemikul Arsy-Mu, para malaikat-Mu, dan seluruh makhluk-Mu, bahwa Engkau adalah Allah; tidak ada sesembahan yang berhak disembah selain Engkau semata, tidak ada sekutu bagi-Mu, dan Muhammad adalah hamba dan Rasul-Mu.",
        "ur": "اے اللہ! میں نے شام کی اس حال میں کہ میں تجھے، تیرے عرش کے حاملین کو، تیرے فرشتوں کو اور تیری تمام مخلوق کو گواہ بناتا ہوں کہ تو ہی اللہ ہے، تیرے سوا کوئی معبود برحق نہیں، تو اکیلا ہے، تیرا کوئی شریک نہیں، اور محمد تیرے بندے اور رسول ہیں۔",
        "hi": "ऐ अल्लाह! मैंने शाम की और तुझे, तेरे अर्श को उठाने वालों को, तेरे फ़रिश्तों को और तेरी सारी मख़लूक़ को गवाह बनाता हूँ कि तू ही अल्लाह है; तेरे सिवा कोई सच्चा पूज्य नहीं, तू अकेला है, तेरा कोई साझी नहीं, और मुहम्मद तेरे बंदे और रसूल हैं।",
    },
)

EVENING_ADHKAR[5] = adhkar_item(
    "اللّهـمَّ ما أَمْسَى بي مِنْ نِعْمَةٍ أو بأَحَدٍ مِنْ خَلْقِكَ، فَمِنْكَ وحدَكَ لا شريكَ لك، فَلَكَ الحمدُ ولكَ الشُّكر.",
    "مرة واحدة",
    "من أذكار المساء",
    {
        "en": "O Allah, whatever blessing has come to me or to any of Your creation this evening is from You alone, with no partner. To You belongs all praise and all thanks.",
        "de": "O Allah, jede Gnade, die mich oder eines Deiner Geschöpfe an diesem Abend erreicht hat, ist von Dir allein, ohne Partner. Dir gebührt alles Lob und aller Dank.",
        "fr": "Ô Allah, tout bienfait qui m’a atteint ce soir, ou qui a atteint l’une de Tes créatures, vient de Toi seul, sans associé. À Toi la louange et à Toi la gratitude.",
        "es": "Oh Allah, cualquier bendición que me haya llegado esta tarde, o que haya llegado a cualquiera de Tus criaturas, viene solo de Ti, sin asociado. A Ti pertenece toda alabanza y todo agradecimiento.",
        "tr": "Allah’ım, bu akşam bana veya yaratıklarından birine ulaşan her nimet yalnızca Sendendir, ortağın yoktur. Hamd de şükür de Sanadır.",
        "id": "Ya Allah, nikmat apa pun yang sampai kepadaku atau kepada salah satu makhluk-Mu pada petang ini, semuanya berasal dari-Mu semata, tidak ada sekutu bagi-Mu. Segala puji dan syukur bagi-Mu.",
        "ur": "اے اللہ! جو بھی نعمت مجھ پر یا تیری کسی مخلوق پر اس شام آئی ہے، وہ صرف تیری طرف سے ہے، تیرا کوئی شریک نہیں۔ پس تمام تعریف اور شکر تیرے ہی لیے ہے۔",
        "hi": "ऐ अल्लाह! जो भी नेमत इस शाम मुझ पर या तेरी किसी मख़लूक़ पर आई है, वह केवल तेरी ओर से है, तेरा कोई साझी नहीं। इसलिए सारी प्रशंसा और शुक्र तेरे ही लिए है।",
    },
)

EVENING_ADHKAR[15] = adhkar_item(
    "أَمْسَيْنا على فِطْرَةِ الإسلام، وعلى كلمةِ الإخلاص، وعلى دينِ نبيّنا محمدٍ ﷺ، وعلى مِلّةِ أبينا إبراهيمَ حنيفًا مسلمًا وما كانَ مِنَ المشركين.",
    "مرة واحدة",
    "من أذكار المساء",
    {
        "en": "We have entered the evening upon the natural way of Islam, the word of sincerity, the religion of our Prophet Muhammad ﷺ, and the way of our father Ibrahim, who was upright and Muslim and was not among the polytheists.",
        "de": "Wir sind in den Abend eingetreten auf der natürlichen Veranlagung des Islam, auf dem Wort der Aufrichtigkeit, auf der Religion unseres Propheten Muhammad ﷺ und auf dem Weg unseres Vaters Ibrahim, der aufrichtig und Muslim war und nicht zu den Götzendienern gehörte.",
        "fr": "Nous sommes entrés dans le soir sur la nature saine de l’Islam, sur la parole de sincérité, sur la religion de notre Prophète Muhammad ﷺ et sur la voie de notre père Ibrahim, droit, soumis à Allah et non parmi les associateurs.",
        "es": "Hemos llegado a la tarde sobre la naturaleza del Islam, sobre la palabra de sinceridad, sobre la religión de nuestro Profeta Muhammad ﷺ y sobre la vía de nuestro padre Ibrahim, recto, musulmán y no de los idólatras.",
        "tr": "İslam fıtratı, ihlas kelimesi, Peygamberimiz Muhammed’in ﷺ dini ve babamız İbrahim’in dosdoğru ve Müslüman olan yolu üzere akşama ulaştık; o müşriklerden değildi.",
        "id": "Kami memasuki petang di atas fitrah Islam, kalimat ikhlas, agama Nabi kami Muhammad ﷺ, dan ajaran bapak kami Ibrahim yang lurus dan berserah diri, dan ia bukan termasuk orang-orang musyrik.",
        "ur": "ہم نے اسلام کی فطرت، اخلاص کے کلمے، اپنے نبی محمد ﷺ کے دین، اور اپنے باپ ابراہیم کی ملت پر شام کی، جو یکسو مسلمان تھے اور مشرکوں میں سے نہ تھے۔",
        "hi": "हमने इस्लाम की फ़ितरत, इख़लास के कलिमे, अपने नबी मुहम्मद ﷺ के धर्म और अपने पिता इब्राहीम के सीधे और मुस्लिम मार्ग पर शाम की, और वे मुश्रिकों में से नहीं थे।",
    },
)